#!/usr/bin/env bash
# lint.sh — Wiki health check. Surfaces orphans, broken cross-refs, missing pages.
#
# Usage: bash lint.sh
#
# Output: wiki/lint-report-<date>.md (and stdout summary)

set -euo pipefail

WIKI_BASE="${SIMON_WIKI_DIR:-$HOME/.claude/wiki}"
WIKI_REPO="${SIMON_WIKI_REPO:-https://github.com/Simon-YHKim/Simon-LLM-Wiki.git}"
REPO_NAME="$(basename "$WIKI_REPO" .git)"
WIKI_DIR="$WIKI_BASE/$REPO_NAME/wiki"

if [ ! -d "$WIKI_DIR" ]; then
  echo "Error: $WIKI_DIR not found. Run wiki-init.sh first." >&2
  exit 1
fi

DATE="$(date +%Y-%m-%d)"
REPORT="$WIKI_DIR/lint-report-$DATE.md"

cd "$WIKI_DIR"

# Collect all wiki page slugs (basename without .md)
mapfile -t PAGES < <(find . -name "*.md" -not -name "lint-report-*" | sed 's|^\./||; s|\.md$||')

# Find all [[wiki-link]] references
mapfile -t LINKS < <(grep -rho '\[\[[^]]*\]\]' . 2>/dev/null | sed 's|\[\[||; s|\]\]||' | sort -u || true)

# Orphan pages: pages with no inbound [[link]]
ORPHANS=()
for page in "${PAGES[@]}"; do
  slug="$(basename "$page")"
  case "$slug" in
    index|log) continue ;;
  esac
  if ! grep -qrh "\[\[$slug\]\]" . 2>/dev/null; then
    ORPHANS+=("$page")
  fi
done

# Broken links: [[X]] referenced but no page X.md exists
BROKEN=()
PAGE_BASENAMES=$(printf '%s\n' "${PAGES[@]}" | xargs -n1 basename 2>/dev/null | sort -u)
for link in "${LINKS[@]}"; do
  if ! echo "$PAGE_BASENAMES" | grep -qx "$link"; then
    BROKEN+=("$link")
  fi
done

# Stale: pages not updated in > 90 days (mtime check)
STALE=()
while IFS= read -r f; do
  STALE+=("$f")
done < <(find . -name "*.md" -mtime +90 -not -name "lint-report-*" 2>/dev/null | sed 's|^\./||')

{
  echo "# Lint Report — $DATE"
  echo ""
  echo "Generated by \`llm-wiki-builder/scripts/lint.sh\`"
  echo ""
  echo "## Summary"
  echo "- Pages scanned: ${#PAGES[@]}"
  echo "- Cross-links found: ${#LINKS[@]}"
  echo "- Orphan pages: ${#ORPHANS[@]}"
  echo "- Broken links: ${#BROKEN[@]}"
  echo "- Stale pages (>90d): ${#STALE[@]}"
  echo ""
  if [ ${#ORPHANS[@]} -gt 0 ]; then
    echo "## Orphan Pages (no inbound links)"
    printf -- '- %s\n' "${ORPHANS[@]}"
    echo ""
  fi
  if [ ${#BROKEN[@]} -gt 0 ]; then
    echo "## Broken Cross-Links"
    printf -- '- [[%s]] — referenced but no page exists\n' "${BROKEN[@]}"
    echo ""
  fi
  if [ ${#STALE[@]} -gt 0 ]; then
    echo "## Stale Pages (>90 days since update)"
    printf -- '- %s\n' "${STALE[@]}"
    echo ""
  fi
  echo "## Suggested Actions"
  echo "- Review orphans: link from related entity/concept pages or delete if obsolete"
  echo "- Fix broken links: create missing pages or correct typos"
  echo "- Refresh stale pages: check if newer sources contradict old claims"
  echo ""
  echo "## Notes"
  echo "Contradiction detection requires LLM analysis (not implemented in this script)."
  echo "Use this report as input: ask the LLM to read flagged pages and surface conflicts."
} > "$REPORT"

echo "[lint] Report written: $REPORT"
echo "[lint] Orphans=${#ORPHANS[@]} Broken=${#BROKEN[@]} Stale=${#STALE[@]}"
